import { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';

export default function OfflineSplash() {
  const navigate = useNavigate();

  useEffect(() => {
    const timer = setTimeout(() => {
      navigate('/aviation/offline/main');
    }, 3000);

    return () => clearTimeout(timer);
  }, [navigate]);

  return (
    <div className="wrap">
      <div className="">
      Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;
      Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;
      Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;
      Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;
      Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;
      Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;
      Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;
      Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;
      Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;
      Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;
      Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;
      Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;
      Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;Splash&nbsp;
      </div>
    </div>
  );
}
